### ISSUE TITLE
The tests are failed on python 3.10

### ISSUE THREAD

**Issue by tuxmaster5000** [msztolcman/fileperms#1]
+ /usr/bin/python3 -m pytest
============================= test session starts ==============================
platform linux -- Python 3.10.4, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: /builddir/build/BUILD/fileperms-1.0.4
collected 22 items

test/test_from_filemode.py ...                                           [ 13%]
test/test_from_int.py ...                                                [ 27%]
test/test_from_octal.py ...                                              [ 40%]
test/test_from_path.py ...                                               [ 54%]
test/test_getter_setter.py ..                                            [ 63%]
test/test_os_chmod.py F                                                  [ 68%]
test/test_pathlib.py F                                                   [ 72%]
test/test_to_filemode.py ..                                              [ 81%]
test/test_to_int.py ..                                                   [ 90%]
test/test_to_octal.py ..                                                 [100%]

=================================== FAILURES ===================================
_______________________________ TestOsChmod.test _______________________________

self = <test_os_chmod.TestOsChmod object at 0x7f2fb0418bb0>

    def test(self):
        perms = '0 1 2 3 4 5 6 7'.split()
        path = tempfile.mkstemp()[1]
    
        try:
            perms = itertools.product(perms, perms, perms, perms)
            for item in perms:
                item = ''.join(item)
                assert len(item) == 4
    
                prm = Permissions.from_octal(item)
>               os.lchmod(path, prm)
E               AttributeError: module 'os' has no attribute 'lchmod'

test/test_os_chmod.py:21: AttributeError
_______________________________ TestPathlib.test _______________________________

self = <test_pathlib.TestPathlib object at 0x7f2fb04187f0>

    def test(self):
        perms = '0 1 2 3 4 5 6 7'.split()
        path = pathlib.Path(tempfile.mkstemp()[1])
    
        try:
            perms = itertools.product(perms, perms, perms, perms)
            for item in perms:
                item = ''.join(item)
                assert len(item) == 4
    
                prm = Permissions.from_octal(item)
>               path.lchmod(prm)

test/test_pathlib.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib64/python3.10/pathlib.py:1196: in lchmod
    self.chmod(mode, follow_symlinks=False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = PosixPath('/tmp/tmp9n1_opd2'), mode = <Permissions(0000)>

    def chmod(self, mode, *, follow_symlinks=True):
        """
        Change the permissions of the path, like os.chmod().
        """
>       self._accessor.chmod(self, mode, follow_symlinks=follow_symlinks)
E       TypeError: 'Permissions' object cannot be interpreted as an integer

/usr/lib64/python3.10/pathlib.py:1189: TypeError
=========================== short test summary info ============================
FAILED test/test_os_chmod.py::TestOsChmod::test - AttributeError: module 'os'...
FAILED test/test_pathlib.py::TestPathlib::test - TypeError: 'Permissions' obj...
========================= 2 failed, 20 passed in 0.18s =========================

**Comment by msztolcman** [comment]
Hello @tuxmaster5000 
Thank you for your report. Issue fixed, unfortunatelly there is no more a way to use `fileperms` without explicit casting to int with `os.chmod` or similar functions :( It must be casted using `int()`.
